services:
  tf:
    privileged: true
    build:
      context: .
    volumes:
      - ..:/src
      - /run/media/pawel/alpha/spatresults/spat:/spat
      - /run/media/pawel/alpha/memmap/:/memmap
      - ../../data/:/data
    environment:
      - PYTHONPATH=/src/train
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
